config:
  namespace: dibidab

GraphicsSettings:
  _flags:
    - not_a_component
    - json_with_keys

  vsync: [ bool, true ]
  fullscreen: [ bool, false ]
  windowSize: [ ivec2, "ivec2(1600, 900)" ]
  printOpenGLMessages: [ bool, false ]
  printOpenGLErrors: [ bool, false ]

  imGuiThemeColor_background: [ u8vec3, "vec3(37, 33, 49)" ]
  imGuiThemeColor_text: [ u8vec3, "vec3(244, 241, 222)" ]
  imGuiThemeColor_main: [ u8vec3,"vec3(218, 17, 94)" ]
  imGuiThemeColor_mainAccent: [ u8vec3,"vec3(121, 35, 89)" ]
  imGuiThemeColor_highLight: [ u8vec3,"vec3(199, 239, 0)" ]

  imGuiFont: std::string

AudioSettings:
  _flags:
    - not_a_component
    - json_with_keys

  masterVolume: [ float, 1. ]
# todo:  categoryVolume: std::map<std::string, float>

KeyInputSettings:
  _flags:
    - not_a_component
    - json_with_keys

  reloadAssets: [ KeyInput::Key, GLFW_KEY_R ]
  toggleFullscreen: [ KeyInput::Key, GLFW_KEY_F11 ]
  toggleDeveloperOptions: [ KeyInput::Key, GLFW_KEY_F3 ]

  inspectEntity: [ KeyInput::Key, GLFW_KEY_I ]
  moveEntity: [ KeyInput::Key, GLFW_KEY_M ]
  moveEntityAndSpawnPoint: [ KeyInput::Key, GLFW_KEY_LEFT_ALT ]
  createEntity: [ KeyInput::Key, GLFW_KEY_INSERT ]

EngineSettings:
  _flags:
    - not_a_component
    - json_with_keys

  graphics: GraphicsSettings
  audio: AudioSettings
  keyInput: KeyInputSettings

  showDeveloperOptions: [ bool, true ]
