name: Build & deploy to gh-pages

on: [push]

jobs:
  
  linux_build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Build linux
      run: |
        sudo apt-get install xorg-dev -y
        sudo apt-get install freeglut3-dev -y
        python initialize_project.py
        cd desktop
        cmake .
        make -j8
        cd out
        mkdir assets
        cp -a ../../assets/. assets/
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: linux_build
        path: desktop/out
        
    
  html_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: lovasoa/setup-emscripten@master
      with:
        emscripten-version: '1.38.47'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Build html
      run: |
        python initialize_project.py
        ls gu/
        cd html
        emconfigure cmake .
        make -j8
    - name: Upload Artifacts # The project is then uploaded as an artifact named 'site'.
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: html/out

  deploy:

    needs: [html_build, linux_build]

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Download HTML build
      uses: actions/download-artifact@v1
      with:
        name: site
        
    - name: Download Linux build
      uses: actions/download-artifact@v1
      with:
        name: linux_build
        
    - name: Zip linux build
      run: |
        cd linux_build
        zip -r ../site/game-linux.zip ./*

    - name: Deploy to GH-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: 'site' # The deployment folder should match the name of the artifact. Even though our project builds into the 'build' folder the artifact name of 'site' must be placed here.
