name: Build & deploy to gh-pages

on: [push]

jobs:

  linux_build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Build linux # running 'cmake .' twice fixes tests being built
      run: |
        sudo apt-get install xorg-dev -y
        sudo apt-get install freeglut3-dev -y
        python initialize_project.py
        cd desktop
        cmake .
        cmake .
        make -j8
        cd out
        mkdir assets
        cp -a ../../assets/. assets/
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: linux_build
        path: desktop/out
        
  windows_build:
    
    runs-on: windows-latest    
    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
    - name: Build windows
      run: |
        python initialize_project.py
        cd desktop
        cmake .
        cmake .
        cmake --build . -j8 --config Release
        cd out/Release/
        rm game.exp game.lib
        mkdir assets
        cp -a ../../../assets/. assets/
        cp ../../bin/gu/bin/openal/Release/OpenAL32.dll .
      shell: bash
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: windows_build
        path: desktop/out/Release

  html_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - uses: lovasoa/setup-emscripten@master
      with:
        emscripten-version: '1.38.47'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Build html
      run: |
        python initialize_project.py
        ls gu/
        cd html
        emconfigure cmake .
        emconfigure cmake .
        make -j8
    - name: Upload Artifacts # The project is then uploaded as an artifact named 'site'.
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: html/out

  deploy:

    needs: [html_build, linux_build, windows_build]

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Download HTML build
      uses: actions/download-artifact@v1
      with:
        name: site
        
    - name: Download Linux build
      uses: actions/download-artifact@v1
      with:
        name: linux_build

    - name: Download Windows build
      uses: actions/download-artifact@v1
      with:
        name: windows_build

    - name: Zip builds
      run: |
        cd linux_build
        zip -r ../site/game-linux.zip ./*
        cd ../windows_build
        zip -r ../site/game-windows.zip ./*

    - name: Deploy to GH-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        SINGLE_COMMIT: true
        FOLDER: 'site' # The deployment folder should match the name of the artifact. Even though our project builds into the 'build' folder the artifact name of 'site' must be placed here.
